erlem_jobeet_homepage:
    pattern:  /
    defaults: { _controller: "ErlemJobeetBundle:Job:index" }

erlem_jobeet_erlem_job:
    resource: "@ErlemJobeetBundle/Resources/config/routing/job.yml"
    prefix:   /job
